#!/usr/bin/env bash
# One-time setup: deploy ballot, register voters, advance to commit phase.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG="$ROOT_DIR/.config"
: "${RPC:?RPC must be set}"
: "${ADMIN_PK:?ADMIN_PK must be set}"
: "${VOTER1_PK:?VOTER1_PK must be set}"
: "${VOTER2_PK:?VOTER2_PK must be set}"
: "${VOTER3_PK:?VOTER3_PK must be set}"
: "${VOTER4_PK:?VOTER4_PK must be set}"
: "${VOTER5_PK:?VOTER5_PK must be set}"

ADMIN_ADDR=$(cast wallet address "$ADMIN_PK")
VOTER1_ADDR=$(cast wallet address "$VOTER1_PK")
VOTER2_ADDR=$(cast wallet address "$VOTER2_PK")
VOTER3_ADDR=$(cast wallet address "$VOTER3_PK")
VOTER4_ADDR=$(cast wallet address "$VOTER4_PK")
VOTER5_ADDR=$(cast wallet address "$VOTER5_PK")

ARBISCAN="${ARBISCAN:-https://sepolia.arbiscan.io}"

# Deploy ballot contract
echo "==> Deploying ballot to Arbitrum Sepolia..."
DEPLOY_OUT=$(cd "$ROOT_DIR" && cargo stylus deploy \
  --endpoint="$RPC" --private-key="$ADMIN_PK" \
  --max-fee-per-gas-gwei 1 --no-verify 2>&1)
echo "$DEPLOY_OUT"
# Strip ANSI codes before parsing the deployed address
CLEAN_OUT=$(echo "$DEPLOY_OUT" | sed 's/\x1b\[[0-9;]*m//g')
BALLOT_ADDR=$(echo "$CLEAN_OUT" | grep -ioE 'deployed code at address: 0x[0-9a-fA-F]+' | grep -ioE '0x[0-9a-fA-F]+')

if [ -z "$BALLOT_ADDR" ]; then
  echo "error: failed to parse deployed address from cargo stylus output"
  exit 1
fi

echo "  Ballot: $ARBISCAN/address/$BALLOT_ADDR"

# Register all 5 voters
echo ""
echo "==> Registering 5 voters..."
for ADDR in "$VOTER1_ADDR" "$VOTER2_ADDR" "$VOTER3_ADDR" "$VOTER4_ADDR" "$VOTER5_ADDR"; do
  cast send --rpc-url "$RPC" --private-key "$ADMIN_PK" \
    "$BALLOT_ADDR" "register(address)" "$ADDR" > /dev/null
  echo "  Registered $ADDR"
done

# Advance to commit phase
echo ""
echo "==> Advancing to commit phase..."
cast send --rpc-url "$RPC" --private-key "$ADMIN_PK" \
  "$BALLOT_ADDR" "advancePhase()" > /dev/null

PHASE=$(cast call --rpc-url "$RPC" "$BALLOT_ADDR" "getPhase()(uint256)")
echo "  Current phase: $PHASE (1=commit)"

# Write config
cat > "$CONFIG" << EOF
# Generated by setup.sh -- safe to commit (no secrets)
BALLOT_ADDR=$BALLOT_ADDR
BALLOT_ARBISCAN=$ARBISCAN/address/$BALLOT_ADDR
ADMIN_ADDR=$ADMIN_ADDR
VOTER1_ADDR=$VOTER1_ADDR
VOTER2_ADDR=$VOTER2_ADDR
VOTER3_ADDR=$VOTER3_ADDR
VOTER4_ADDR=$VOTER4_ADDR
VOTER5_ADDR=$VOTER5_ADDR
EOF

echo ""
echo "Config written to .config"
echo ""
echo "Done! You can now run: make demo"
