#!/usr/bin/env bash
# One-time setup: deploy MockERC20, mint tokens to buyer, write .config.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG="$ROOT_DIR/.config"
: "${RPC:?RPC must be set}"
: "${BUYER_PK:?BUYER_PK must be set (add it to .env)}"
: "${SELLER_PK:?SELLER_PK must be set (add it to .env)}"

BUYER_ADDR=$(cast wallet address "$BUYER_PK")
SELLER_ADDR=$(cast wallet address "$SELLER_PK")

# Deploy MockERC20 to a tempdir
echo "==> Deploying MockERC20 to Arbitrum Sepolia..."
TMPDIR=$(mktemp -d)
mkdir -p "$TMPDIR/src"
cp "$SCRIPT_DIR/MockERC20.sol" "$TMPDIR/src/"
cat > "$TMPDIR/foundry.toml" << 'TOML'
[profile.default]
src = "src"
out = "out"
libs = []
solc_version = "0.8.24"
TOML

USDC_ADDR=$(forge create \
  --broadcast \
  --rpc-url "$RPC" \
  --private-key "$BUYER_PK" \
  --json \
  --root "$TMPDIR" \
  src/MockERC20.sol:MockERC20 | jq -r '.contractAddress // .deployedTo')

# Verify on Arbiscan
echo "==> Verifying on Arbiscan..."
forge verify-contract \
  --chain arbitrum-sepolia \
  --root "$TMPDIR" \
  "$USDC_ADDR" \
  src/MockERC20.sol:MockERC20 || echo "Warning: verification failed (may need ETHERSCAN_API_KEY)"

rm -rf "$TMPDIR"

# Mint tokens to buyer
echo ""
echo "==> Minting 100,000 USDC to buyer ($BUYER_ADDR)..."
cast send --rpc-url "$RPC" --private-key "$BUYER_PK" \
  "$USDC_ADDR" "mint(address,uint256)" "$BUYER_ADDR" "100000000000" > /dev/null

# Write config
cat > "$CONFIG" << EOF
# Generated by setup.sh -- safe to commit (no secrets)
USDC_ADDR=$USDC_ADDR
USDC_ARBISCAN=https://sepolia.arbiscan.io/address/$USDC_ADDR
BUYER_ADDR=$BUYER_ADDR
SELLER_ADDR=$SELLER_ADDR
EOF

echo ""
echo "Config written to .config:"
cat "$CONFIG"
echo ""
echo "USDC: https://sepolia.arbiscan.io/address/$USDC_ADDR"
echo ""
echo "Done! You can now run: make demo"
